import Foundation
import CryptoKit

/// The library of pre-generated voice clips, addressed by the text they speak.
///
/// A clip's filename is `<textHash16>-<audioHash8>.mp3`, where `textHash16`
/// is the first 16 hex characters of the SHA-256 of the normalized line text
/// (see `normalize`) and `audioHash8` fingerprints the audio bytes so a
/// re-recorded voice for the same line gets a new filename. Clips are
/// generated by tools/generate_voice.py and reach the device two ways:
///
///   1. Bundled — Voice/clips/ shipped inside the app
///   2. Downloaded — cached by PackSync in Application Support/Voice/clips
///
/// Narrator asks `clipURL(for:)` before falling back to text-to-speech, so a
/// missing clip is never an error — the line is just synthesized instead.
/// Main-thread only, like the rest of the audio layer.
final class VoiceBank {
    static let shared = VoiceBank()

    /// textHash16 → playable clip file. Downloaded clips win over bundled
    /// ones (a re-generated voice reaches devices before the next app build).
    private var clips: [String: URL] = [:]

    /// Every clip filename available locally, for PackSync's "do I already
    /// have this file" checks (exact filename, so new audio for an old line
    /// is still seen as missing).
    private var filenames: Set<String> = []

    private init() {
        reload()
    }

    // MARK: Lookup

    func clipURL(for text: String) -> URL? {
        clips[Self.textHash(text)]
    }

    func hasClip(filename: String) -> Bool {
        filenames.contains(filename)
    }

    // MARK: Hashing

    /// Whitespace-normalized form of a spoken line — must match the
    /// normalization in tools/generate_voice.py exactly.
    static func normalize(_ text: String) -> String {
        text.split(whereSeparator: \.isWhitespace).joined(separator: " ")
    }

    static func textHash(_ text: String) -> String {
        let digest = SHA256.hash(data: Data(normalize(text).utf8))
        return digest.map { String(format: "%02x", $0) }.joined().prefix(16).lowercased()
    }

    // MARK: Loading

    /// Re-scan bundle and downloads. Called at startup and by PackSync after
    /// new clips land.
    func reload() {
        var found: [String: URL] = [:]
        var names: Set<String> = []

        // Bundled first, then downloaded, so downloads override on collision.
        for url in Self.bundledClipURLs() + Self.downloadedClipURLs() {
            let stem = url.deletingPathExtension().lastPathComponent
            guard let textHash = stem.split(separator: "-").first else { continue }
            found[String(textHash)] = url
            names.insert(url.lastPathComponent)
        }
        clips = found
        filenames = names
    }

    private static func bundledClipURLs() -> [URL] {
        // Folder-synced Xcode projects may flatten resources or keep the
        // folder structure; look in both places, like ContentLibrary does.
        var urls: [URL] = []
        for subdirectory in [nil, "Voice", "clips", "Voice/clips"] {
            urls += Bundle.main.urls(forResourcesWithExtension: "mp3",
                                     subdirectory: subdirectory) ?? []
        }
        var seen = Set<String>()
        return urls.filter { seen.insert($0.lastPathComponent).inserted }
    }

    private static func downloadedClipURLs() -> [URL] {
        let contents = (try? FileManager.default.contentsOfDirectory(
            at: downloadsDirectory, includingPropertiesForKeys: nil)) ?? []
        return contents.filter { $0.pathExtension.lowercased() == "mp3" }
    }

    /// Where PackSync caches downloaded clips. Created on first use.
    static var downloadsDirectory: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? FileManager.default.temporaryDirectory
        let directory = base.appendingPathComponent("Voice/clips", isDirectory: true)
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory
    }
}
